services:

  fido2-server:
    container_name: fido2_server_demo
    build: ./fido2_server
    ports:
      - "3001:3001"
    depends_on:
      - fido2-db
    environment:
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: root
      DB_DATABASE: fidodb
      CHOKIDAR_USEPOLLING: 'true'
  
  fido2-db:
    container_name: fido2-db_demo
    image:  mysql:latest
    expose : 
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fidodb
      MYSQL_USER: fido-user
      MYSQL_PASSWORD: password
    volumes:
      - "fido2_db_data:/var/lib/mysql"
      - "./backup:/backup"
      - "./fido2_server/db/01_create_users.sql:/docker-entrypoint-initdb.d/01_create_users.sql"
      - "./fido2_server/db/02_create_credentials.sql:/docker-entrypoint-initdb.d/02_create_credentials.sql"

volumes:
  fido2_db_data:
